import { afterEach, describe, expect, jest, test } from '@jest/globals'
import { createHash } from 'crypto'
import fsp from 'fs/promises'
import os from 'os'
import path from 'path'
import {
  INSTALLER_MANAGED_ENV_KEYS,
  RUNTIME_WINDOWS_ENV_FILE,
  applyRuntimeWindowsEnvironment,
  assertRegularRuntimeEnvironmentFile,
  loadRuntimeWindowsEnvironment,
  parseRuntimeWindowsEnvironment,
  startWindowsHostAgentBootstrap,
  verifyWindowsRuntimeEnvAcl,
} from '../../../packages/windows-host-agent/src/bootstrap.js'

const STRONG_API_KEY = 'a'.repeat(32)
const STRONG_RUNTIME_API_KEY = 'b'.repeat(32)
const temporaryDirectories = new Set<string>()

async function createTemporaryProject(content: string | Buffer): Promise<string> {
  const projectRoot = await fsp.mkdtemp(path.join(os.tmpdir(), 'rikune-host-bootstrap-'))
  temporaryDirectories.add(projectRoot)
  await fsp.writeFile(path.join(projectRoot, RUNTIME_WINDOWS_ENV_FILE), content)
  return projectRoot
}

afterEach(async () => {
  await Promise.all(
    Array.from(temporaryDirectories).map((temporaryDirectory) =>
      fsp.rm(temporaryDirectory, { recursive: true, force: true })
    )
  )
  temporaryDirectories.clear()
})

describe('Windows Host Agent secure bootstrap parser', () => {
  test('accepts only the installer-managed whitelist and preserves values after the first equals', () => {
    expect(INSTALLER_MANAGED_ENV_KEYS).toEqual([
      'HOST_AGENT_PORT',
      'HOST_AGENT_BIND_HOST',
      'HOST_AGENT_RUNTIME_BIND_HOST',
      'HOST_AGENT_RUNTIME_ADVERTISED_HOST',
      'HOST_AGENT_API_KEY',
      'HOST_AGENT_RUNTIME_API_KEY',
      'HOST_AGENT_WORKSPACE',
      'HOST_AGENT_NODE_PATH',
      'HOST_AGENT_PYTHON_PATH',
      'HOST_AGENT_BACKEND',
      'HOST_AGENT_HYPERV_VM_NAME',
      'HOST_AGENT_HYPERV_SNAPSHOT_NAME',
      'HOST_AGENT_HYPERV_RUNTIME_ENDPOINT',
      'HOST_AGENT_HYPERV_RESTORE_ON_RELEASE',
      'HOST_AGENT_HYPERV_STOP_ON_RELEASE',
    ])

    const values = parseRuntimeWindowsEnvironment(
      [
        '# generated by the Windows installer',
        `HOST_AGENT_API_KEY=${STRONG_API_KEY}`,
        `HOST_AGENT_RUNTIME_API_KEY=${STRONG_RUNTIME_API_KEY}`,
        'HOST_AGENT_RUNTIME_BIND_HOST=127.0.0.1',
        'HOST_AGENT_RUNTIME_ADVERTISED_HOST=host.docker.internal',
        'HOST_AGENT_PORT=18082',
        'HOST_AGENT_WORKSPACE=C:\\runtime=workspace',
        'HOST_AGENT_HYPERV_SNAPSHOT_NAME=',
        '',
      ].join('\n')
    )

    expect(values).toEqual({
      HOST_AGENT_API_KEY: STRONG_API_KEY,
      HOST_AGENT_RUNTIME_API_KEY: STRONG_RUNTIME_API_KEY,
      HOST_AGENT_RUNTIME_BIND_HOST: '127.0.0.1',
      HOST_AGENT_RUNTIME_ADVERTISED_HOST: 'host.docker.internal',
      HOST_AGENT_PORT: '18082',
      HOST_AGENT_WORKSPACE: 'C:\\runtime=workspace',
      HOST_AGENT_HYPERV_SNAPSHOT_NAME: '',
    })
  })

  test.each([
    [`HOST_AGENT_API_KEY=${STRONG_API_KEY}\nNODE_OPTIONS=--inspect`, 'Unknown'],
    [`HOST_AGENT_API_KEY=${STRONG_API_KEY}\nHOST_AGENT_API_KEY=${'b'.repeat(32)}`, 'Duplicate'],
    [`HOST_AGENT_API_KEY=${STRONG_API_KEY}\r\nHOST_AGENT_PORT=18082`, 'LF-only'],
    [`HOST_AGENT_API_KEY=${STRONG_API_KEY}\0HOST_AGENT_PORT=18082`, 'NUL'],
    ['HOST_AGENT_API_KEY', 'Invalid runtime environment entry'],
  ])('rejects invalid or injected content', (content, expectedMessage) => {
    expect(() => parseRuntimeWindowsEnvironment(content)).toThrow(expectedMessage)
  })

  test.each([
    ['', 'HOST_AGENT_API_KEY'],
    ['HOST_AGENT_PORT=18082\n', 'HOST_AGENT_API_KEY'],
    ['HOST_AGENT_API_KEY=too-short\n', 'at least 32'],
    [`HOST_AGENT_API_KEY=${' '.repeat(32)}\n`, 'at least 32'],
  ])('fails closed without a strong Host Agent API key', (content, expectedMessage) => {
    expect(() => parseRuntimeWindowsEnvironment(content)).toThrow(expectedMessage)
  })

  test.each([
    [`HOST_AGENT_API_KEY=${STRONG_API_KEY}\n`, 'HOST_AGENT_RUNTIME_API_KEY'],
    [
      `HOST_AGENT_API_KEY=${STRONG_API_KEY}\nHOST_AGENT_RUNTIME_API_KEY=too-short\n`,
      'at least 32',
    ],
    [
      `HOST_AGENT_API_KEY=${STRONG_API_KEY}\nHOST_AGENT_RUNTIME_API_KEY=${STRONG_API_KEY}\n`,
      'must be distinct',
    ],
  ])('fails closed without a strong distinct Runtime Node API key', (content, expectedMessage) => {
    expect(() => parseRuntimeWindowsEnvironment(content)).toThrow(expectedMessage)
  })
})

describe('Windows Host Agent protected environment loading', () => {
  test('verifies the fixed project-root file before returning parsed values', async () => {
    const projectRoot = await createTemporaryProject(
      `HOST_AGENT_API_KEY=${STRONG_API_KEY}\nHOST_AGENT_RUNTIME_API_KEY=${STRONG_RUNTIME_API_KEY}\nHOST_AGENT_PORT=18082\n`
    )
    const verifyAcl = jest.fn(async () => undefined)

    await expect(loadRuntimeWindowsEnvironment({ projectRoot, verifyAcl })).resolves.toEqual({
      HOST_AGENT_API_KEY: STRONG_API_KEY,
      HOST_AGENT_RUNTIME_API_KEY: STRONG_RUNTIME_API_KEY,
      HOST_AGENT_PORT: '18082',
    })
    expect(verifyAcl).toHaveBeenCalledWith(path.join(projectRoot, RUNTIME_WINDOWS_ENV_FILE))
  })

  test('rejects ACL evidence that does not match the bytes read by Node', async () => {
    const content = `HOST_AGENT_API_KEY=${STRONG_API_KEY}\n`
    const projectRoot = await createTemporaryProject(content)

    await expect(
      loadRuntimeWindowsEnvironment({
        projectRoot,
        verifyAcl: async () => ({
          sha256: createHash('sha256').update('different content').digest('hex'),
          size: Buffer.byteLength(content),
        }),
      })
    ).rejects.toThrow('changed after ACL verification')
  })

  test('rejects oversized ACL evidence before reading the file', async () => {
    const projectRoot = await createTemporaryProject(`HOST_AGENT_API_KEY=${STRONG_API_KEY}\n`)

    await expect(
      loadRuntimeWindowsEnvironment({
        projectRoot,
        verifyAcl: async () => ({
          sha256: 'a'.repeat(64),
          size: 64 * 1024 + 1,
        }),
      })
    ).rejects.toThrow('maximum allowed size')
  })

  test('rejects non-files and symbolic-link metadata before parsing', async () => {
    expect(() =>
      assertRegularRuntimeEnvironmentFile({
        isFile: () => true,
        isSymbolicLink: () => true,
      })
    ).toThrow('symlink or reparse point')
    expect(() =>
      assertRegularRuntimeEnvironmentFile({
        isFile: () => false,
        isSymbolicLink: () => false,
      })
    ).toThrow('regular file')

    const projectRoot = await fsp.mkdtemp(path.join(os.tmpdir(), 'rikune-host-bootstrap-'))
    temporaryDirectories.add(projectRoot)
    await fsp.mkdir(path.join(projectRoot, RUNTIME_WINDOWS_ENV_FILE))
    const verifyAcl = jest.fn(async () => undefined)
    await expect(loadRuntimeWindowsEnvironment({ projectRoot, verifyAcl })).rejects.toThrow(
      'regular file'
    )
    expect(verifyAcl).not.toHaveBeenCalled()
  })

  test('rejects invalid UTF-8 after ACL verification', async () => {
    const projectRoot = await createTemporaryProject(Buffer.from([0xc3, 0x28]))
    await expect(
      loadRuntimeWindowsEnvironment({ projectRoot, verifyAcl: async () => undefined })
    ).rejects.toThrow('valid UTF-8')
  })
})

describe('Windows Host Agent startup ordering', () => {
  test('routes development and direct package startup through the secure bootstrap', async () => {
    const packageJson = JSON.parse(
      await fsp.readFile(
        path.resolve(process.cwd(), 'packages/windows-host-agent/package.json'),
        'utf8'
      )
    ) as { scripts?: Record<string, string> }

    expect(packageJson.scripts?.dev).toBe('tsx watch src/bootstrap.ts')
    expect(packageJson.scripts?.start).toBe('node dist/bootstrap.js')
    expect(packageJson.scripts?.test).toContain('windows-host-agent-bootstrap.test.ts')
  })

  test('overrides stale process values only after validation and before importing index.js', async () => {
    const projectRoot = await createTemporaryProject(
      `HOST_AGENT_API_KEY=${STRONG_API_KEY}\nHOST_AGENT_RUNTIME_API_KEY=${STRONG_RUNTIME_API_KEY}\nHOST_AGENT_PORT=18082\nHOST_AGENT_HYPERV_VM_NAME=\n`
    )
    const environment: NodeJS.ProcessEnv = {
      HOST_AGENT_API_KEY: 'stale-pm2-secret-that-must-be-overridden',
      HOST_AGENT_PORT: '19999',
      HOST_AGENT_HYPERV_VM_NAME: 'stale-vm-name',
      HOST_AGENT_HYPERV_STOP_ON_RELEASE: 'true',
      UNRELATED_VALUE: 'preserved',
    }
    const startHostAgentServer = jest.fn()
    const importHostAgent = jest.fn(async () => {
      expect(environment.HOST_AGENT_API_KEY).toBe(STRONG_API_KEY)
      expect(environment.HOST_AGENT_RUNTIME_API_KEY).toBe(STRONG_RUNTIME_API_KEY)
      expect(environment.HOST_AGENT_PORT).toBe('18082')
      expect(environment.HOST_AGENT_HYPERV_VM_NAME).toBe('')
      expect(environment.HOST_AGENT_HYPERV_STOP_ON_RELEASE).toBeUndefined()
      expect(environment.UNRELATED_VALUE).toBe('preserved')
      return { startHostAgentServer }
    })

    await startWindowsHostAgentBootstrap({
      projectRoot,
      processEnvironment: environment,
      verifyAcl: async () => undefined,
      importHostAgent,
    })

    expect(importHostAgent).toHaveBeenCalledTimes(1)
    expect(startHostAgentServer).toHaveBeenCalledTimes(1)
  })

  test('does not mutate the environment or import the Host Agent when ACL verification fails', async () => {
    const projectRoot = await createTemporaryProject(
      `HOST_AGENT_API_KEY=${STRONG_API_KEY}\nHOST_AGENT_PORT=18082\n`
    )
    const environment: NodeJS.ProcessEnv = {
      HOST_AGENT_API_KEY: 'stale-value',
      HOST_AGENT_PORT: '19999',
    }
    const importHostAgent = jest.fn(async () => ({ startHostAgentServer: jest.fn() }))

    await expect(
      startWindowsHostAgentBootstrap({
        projectRoot,
        processEnvironment: environment,
        verifyAcl: async () => {
          throw new Error('ACL rejected')
        },
        importHostAgent,
      })
    ).rejects.toThrow('ACL rejected')
    expect(environment).toEqual({
      HOST_AGENT_API_KEY: 'stale-value',
      HOST_AGENT_PORT: '19999',
    })
    expect(importHostAgent).not.toHaveBeenCalled()
  })

  test('rolls back a partial environment write if an assignment fails', () => {
    const backing: NodeJS.ProcessEnv = { HOST_AGENT_API_KEY: 'old-value' }
    let assignmentFailed = false
    const environment = new Proxy(backing, {
      set(target, property, value) {
        if (property === 'HOST_AGENT_API_KEY' && !assignmentFailed) {
          assignmentFailed = true
          throw new Error('write denied')
        }
        return Reflect.set(target, property, value)
      },
    })

    expect(() =>
      applyRuntimeWindowsEnvironment(
        {
          HOST_AGENT_API_KEY: STRONG_API_KEY,
          HOST_AGENT_PORT: '18082',
        },
        environment
      )
    ).toThrow('write denied')
    expect(backing).toEqual({ HOST_AGENT_API_KEY: 'old-value' })
  })
})

describe('real Windows ACL verifier command contract', () => {
  test('uses trusted PowerShell with a sanitized child environment and no secret in argv', async () => {
    const targetPath = 'C:\\rikune\\.env.runtime-windows'
    const secret = 'secret-must-not-enter-child-argv-or-environment'
    const runCommand = jest.fn(async () => ({
      stdout: JSON.stringify({
        marker: 'RIKUNE_WINDOWS_RUNTIME_ENV_ACL_V1',
        sha256: 'a'.repeat(64),
        size: 123,
      }),
      stderr: '',
    }))

    await expect(
      verifyWindowsRuntimeEnvAcl(targetPath, {
        platform: 'win32',
        environment: {
          SystemRoot: 'C:\\Windows',
          PATH: 'C:\\Windows\\System32',
          PSModulePath: 'C:\\attacker-controlled-modules',
          HOST_AGENT_API_KEY: secret,
          RUNTIME_API_KEY: secret,
        },
        runCommand,
      })
    ).resolves.toEqual({ sha256: 'a'.repeat(64), size: 123 })

    const [command, args, options] = runCommand.mock.calls[0]!
    expect(command).toBe('C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe')
    expect(JSON.stringify(args)).not.toContain(secret)
    expect(JSON.stringify(args)).not.toContain(targetPath)
    expect(options.env.RIKUNE_HOST_AGENT_ENV_PATH).toBe(targetPath)
    expect(options.env.HOST_AGENT_API_KEY).toBeUndefined()
    expect(options.env.RUNTIME_API_KEY).toBeUndefined()
    expect(options.env.PATH).toBeUndefined()
    expect(options.env.PSModulePath).toBeUndefined()
    expect(options.windowsHide).toBe(true)

    const encodedCommand = args[args.indexOf('-EncodedCommand') + 1]!
    const verifierScript = Buffer.from(encodedCommand, 'base64').toString('utf16le')
    expect(verifierScript).toContain('FileAttributes]::ReparsePoint')
    expect(verifierScript).toContain('File]::GetAccessControl')
    expect(verifierScript).toContain('AreAccessRulesProtected')
    expect(verifierScript).toContain('$acl.GetOwner(')
    expect(verifierScript).toContain('$allowedSids -notcontains $ownerSid')
    expect(verifierScript).toContain("'S-1-5-18'")
    expect(verifierScript).toContain("'S-1-5-32-544'")
    expect(verifierScript).toContain('FileSystemRights]::FullControl')
    expect(verifierScript).not.toContain('Get-Acl')
    expect(verifierScript).not.toContain('Get-Item')
    expect(verifierScript).not.toContain('ConvertTo-Json')
  })
})
