#!/usr/bin/env node
/**
 * Plugin template scaffolding — creates a new plugin skeleton.
 *
 * Usage:
 *   node scripts/create-plugin.js <plugin-id> [--name "Display Name"]
 *
 * Example:
 *   node scripts/create-plugin.js memory-forensics --name "Memory Forensics"
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const pluginsDir = path.resolve(__dirname, '..', 'plugins')

function kebabToCamel(s) {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase())
}

function kebabToTitle(s) {
  return s.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join(' ')
}

const args = process.argv.slice(2)
if (args.length === 0 || args[0] === '--help') {
  console.log('Usage: node scripts/create-plugin.js <plugin-id> [--name "Display Name"]')
  process.exit(0)
}

const pluginId = args[0]
const nameIdx = args.indexOf('--name')
const displayName = nameIdx >= 0 && args[nameIdx + 1] ? args[nameIdx + 1] : kebabToTitle(pluginId)
const camelId = kebabToCamel(pluginId)

if (!/^[a-z][a-z0-9-]*$/.test(pluginId)) {
  console.error('Error: plugin-id must be kebab-case (e.g. "my-plugin")')
  process.exit(1)
}

const pluginDir = path.join(pluginsDir, pluginId)

if (fs.existsSync(pluginDir)) {
  console.error(`Error: plugin directory already exists: ${pluginDir}`)
  process.exit(1)
}

fs.mkdirSync(pluginDir, { recursive: true })

// --- index.ts ---
const indexContent = `/**
 * Plugin: ${displayName}
 * Auto-generated by scripts/create-plugin.js
 */

import type {
  Plugin,
  PluginContext,
  PluginServerInterface,
  PluginToolDeps,
  ToolResult,
} from '../../packages/plugin-sdk/src/index.js'

const plugin: Plugin = {
  id: '${pluginId}',
  name: '${displayName}',
  description: '${displayName} plugin tools and integration.',
  version: '0.1.0',
  executionDomain: 'both',
  dependencies: [],
  configSchema: [
    // { envVar: 'MY_TOOL_PATH', description: 'Path to external tool', required: false },
  ],
  surfaceRules: { tier: 3, category: 'static-analysis' },

  check() {
    // Return false to skip loading when prerequisites are missing.
    return true
  },

  register(server: PluginServerInterface, _deps: PluginToolDeps, ctx?: PluginContext): string[] {
    const tools: string[] = []

    server.registerTool(
      {
        name: '${pluginId}.hello',
        description: '${displayName} — baseline scaffold tool',
        inputSchema: {
          type: 'object',
          properties: {
            sample_id: { type: 'string', description: 'Sample ID to analyze' },
          },
          required: ['sample_id'],
        },
      },
      async (args: { sample_id: string }): Promise<ToolResult> => ({
        content: [{
          type: 'text',
          text: JSON.stringify({
            plugin: '${pluginId}',
            message: 'Replace scaffold output with a real implementation.',
            sample_id: args.sample_id,
            plugin_context: ctx?.pluginId ?? '${pluginId}',
          }),
        }],
      })
    )
    tools.push('${pluginId}.hello')

    return tools
  },

  async teardown() {
    // Cleanup resources if needed.
  },
}

export default plugin
`

fs.writeFileSync(path.join(pluginDir, 'index.ts'), indexContent)

console.log(`✓ Created plugin scaffold at plugins/${pluginId}/`)
console.log(`  - plugins/${pluginId}/index.ts`)
console.log(`\nNext steps:`)
console.log(`  1. Replace the scaffold tool implementation in plugins/${pluginId}/index.ts`)
console.log(`  2. Add any systemDeps/configSchema entries your plugin needs`)
console.log(`  3. Restart the server — the plugin is auto-discovered`)
